# Generated by Django 3.2.8 on 2021-10-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='id',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='sno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
