# Generated by Django 3.2.8 on 2022-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
